export type Testament = "OT" | "NT";

export type Genre =
  | "Law"
  | "History"
  | "Wisdom"
  | "Major Prophets"
  | "Minor Prophets"
  | "Gospels"
  | "Acts"
  | "Pauline Epistles"
  | "General Epistles"
  | "Apocalyptic";

export interface Book {
  /** bolls.life numeric book id (1–66) */
  id: number;
  slug: string;
  name: string;
  abbr: string;
  chapters: number;
  testament: Testament;
  genre: Genre;
  author: string;
  date: string;
  summary: string;
  themes: string[];
  keyVerse: { ref: string; chapter: number; verse: number };
}

export const BOOKS: Book[] = [
  { id: 1, slug: "genesis", name: "Genesis", abbr: "Gen", chapters: 50, testament: "OT", genre: "Law", author: "Moses", date: "c. 1445–1405 BC", summary: "The book of beginnings: creation, the fall, the flood, and God's covenant with Abraham, Isaac, Jacob, and Joseph. God chooses a family through whom He will bless all nations.", themes: ["Creation", "Covenant", "Promise", "Providence"], keyVerse: { ref: "Genesis 12:2", chapter: 12, verse: 2 } },
  { id: 2, slug: "exodus", name: "Exodus", abbr: "Exod", chapters: 40, testament: "OT", genre: "Law", author: "Moses", date: "c. 1445–1405 BC", summary: "God redeems Israel from slavery in Egypt through mighty acts, gives the Law at Sinai, and comes to dwell among His people in the tabernacle.", themes: ["Redemption", "Deliverance", "Law", "God's presence"], keyVerse: { ref: "Exodus 14:13", chapter: 14, verse: 13 } },
  { id: 3, slug: "leviticus", name: "Leviticus", abbr: "Lev", chapters: 27, testament: "OT", genre: "Law", author: "Moses", date: "c. 1445–1405 BC", summary: "A holy God teaches His people how to approach Him: sacrifices, priesthood, purity, and the great Day of Atonement. \"Be holy, for I am holy.\"", themes: ["Holiness", "Atonement", "Sacrifice", "Worship"], keyVerse: { ref: "Leviticus 19:2", chapter: 19, verse: 2 } },
  { id: 4, slug: "numbers", name: "Numbers", abbr: "Num", chapters: 36, testament: "OT", genre: "Law", author: "Moses", date: "c. 1445–1405 BC", summary: "Israel journeys from Sinai toward Canaan but rebels in unbelief, wandering forty years in the wilderness while God remains faithful to a new generation.", themes: ["Faithfulness", "Unbelief", "Wilderness", "Discipline"], keyVerse: { ref: "Numbers 6:24", chapter: 6, verse: 24 } },
  { id: 5, slug: "deuteronomy", name: "Deuteronomy", abbr: "Deut", chapters: 34, testament: "OT", genre: "Law", author: "Moses", date: "c. 1405 BC", summary: "Moses' farewell sermons on the plains of Moab: remember the LORD, love Him with all your heart, and choose life by keeping His covenant.", themes: ["Covenant renewal", "Love for God", "Obedience", "Remembrance"], keyVerse: { ref: "Deuteronomy 6:5", chapter: 6, verse: 5 } },
  { id: 6, slug: "joshua", name: "Joshua", abbr: "Josh", chapters: 24, testament: "OT", genre: "History", author: "Joshua", date: "c. 1405–1385 BC", summary: "God fulfills His promise as Joshua leads Israel to conquer and settle the promised land. Not one word of God's good promises fails.", themes: ["Promise fulfilled", "Courage", "Conquest", "Inheritance"], keyVerse: { ref: "Joshua 1:9", chapter: 1, verse: 9 } },
  { id: 7, slug: "judges", name: "Judges", abbr: "Judg", chapters: 21, testament: "OT", genre: "History", author: "Unknown (traditionally Samuel)", date: "c. 1045–1000 BC", summary: "A dark spiral of sin, oppression, crying out, and deliverance. Everyone did what was right in their own eyes — Israel needs a righteous king.", themes: ["Sin cycle", "Deliverance", "Mercy", "Need for a king"], keyVerse: { ref: "Judges 21:25", chapter: 21, verse: 25 } },
  { id: 8, slug: "ruth", name: "Ruth", abbr: "Ruth", chapters: 4, testament: "OT", genre: "History", author: "Unknown", date: "c. 1000 BC", summary: "A Moabite widow's loyal love and a kinsman-redeemer's kindness weave into God's plan, placing Ruth in the family line of King David and the Messiah.", themes: ["Loyal love", "Redemption", "Providence", "Inclusion"], keyVerse: { ref: "Ruth 1:16", chapter: 1, verse: 16 } },
  { id: 9, slug: "1-samuel", name: "1 Samuel", abbr: "1Sam", chapters: 31, testament: "OT", genre: "History", author: "Samuel, Nathan, Gad", date: "c. 930 BC", summary: "Israel transitions from judges to kings: Samuel the prophet, Saul the failed king, and David the man after God's own heart.", themes: ["Kingship", "Obedience over sacrifice", "God's choice", "The heart"], keyVerse: { ref: "1 Samuel 16:7", chapter: 16, verse: 7 } },
  { id: 10, slug: "2-samuel", name: "2 Samuel", abbr: "2Sam", chapters: 24, testament: "OT", genre: "History", author: "Nathan, Gad", date: "c. 930 BC", summary: "David's reign: triumphs, the everlasting covenant of an eternal throne, and the devastating fallout of his sin with Bathsheba.", themes: ["Davidic covenant", "Kingdom", "Sin's consequences", "Grace"], keyVerse: { ref: "2 Samuel 7:16", chapter: 7, verse: 16 } },
  { id: 11, slug: "1-kings", name: "1 Kings", abbr: "1Kgs", chapters: 22, testament: "OT", genre: "History", author: "Unknown (traditionally Jeremiah)", date: "c. 560–540 BC", summary: "Solomon's glory and the temple's construction give way to a divided kingdom and a parade of kings, with Elijah confronting idolatry.", themes: ["Wisdom", "Temple", "Division", "Idolatry"], keyVerse: { ref: "1 Kings 18:21", chapter: 18, verse: 21 } },
  { id: 12, slug: "2-kings", name: "2 Kings", abbr: "2Kgs", chapters: 25, testament: "OT", genre: "History", author: "Unknown (traditionally Jeremiah)", date: "c. 560–540 BC", summary: "Elisha's ministry, persistent rebellion, and the fall of both kingdoms — Israel to Assyria, Judah to Babylon — just as the prophets warned.", themes: ["Judgment", "Prophecy fulfilled", "Exile", "Remnant"], keyVerse: { ref: "2 Kings 17:13", chapter: 17, verse: 13 } },
  { id: 13, slug: "1-chronicles", name: "1 Chronicles", abbr: "1Chr", chapters: 29, testament: "OT", genre: "History", author: "Ezra (traditionally)", date: "c. 450–430 BC", summary: "A post-exile retelling of Israel's story centered on David, the ark, worship, and preparations for the temple — hope for a restored people.", themes: ["Worship", "Davidic line", "God's faithfulness", "Identity"], keyVerse: { ref: "1 Chronicles 16:11", chapter: 16, verse: 11 } },
  { id: 14, slug: "2-chronicles", name: "2 Chronicles", abbr: "2Chr", chapters: 36, testament: "OT", genre: "History", author: "Ezra (traditionally)", date: "c. 450–430 BC", summary: "From Solomon's temple to the exile, the Chronicler highlights kings who sought the LORD and the healing that comes with humble prayer.", themes: ["Temple", "Revival", "Prayer", "Seeking God"], keyVerse: { ref: "2 Chronicles 7:14", chapter: 7, verse: 14 } },
  { id: 15, slug: "ezra", name: "Ezra", abbr: "Ezra", chapters: 10, testament: "OT", genre: "History", author: "Ezra", date: "c. 440 BC", summary: "Exiles return to rebuild the temple and, under Ezra the scribe, to rebuild their lives around God's Word.", themes: ["Restoration", "Scripture", "Repentance", "Providence"], keyVerse: { ref: "Ezra 7:10", chapter: 7, verse: 10 } },
  { id: 16, slug: "nehemiah", name: "Nehemiah", abbr: "Neh", chapters: 13, testament: "OT", genre: "History", author: "Nehemiah, Ezra", date: "c. 430 BC", summary: "A cupbearer becomes a wall-builder: Nehemiah leads Jerusalem's restoration through prayer, grit, and covenant renewal.", themes: ["Leadership", "Prayer", "Perseverance", "Renewal"], keyVerse: { ref: "Nehemiah 8:10", chapter: 8, verse: 10 } },
  { id: 17, slug: "esther", name: "Esther", abbr: "Esth", chapters: 10, testament: "OT", genre: "History", author: "Unknown (possibly Mordecai)", date: "c. 460 BC", summary: "God's name never appears, yet His hand is everywhere: a Jewish queen risks everything and her people are saved \"for such a time as this.\"", themes: ["Providence", "Courage", "Deliverance", "Reversal"], keyVerse: { ref: "Esther 4:14", chapter: 4, verse: 14 } },
  { id: 18, slug: "job", name: "Job", abbr: "Job", chapters: 42, testament: "OT", genre: "Wisdom", author: "Unknown", date: "Unknown (patriarchal era setting)", summary: "A righteous sufferer wrestles with God amid unexplained pain. The answer is not a reason but a Person: the LORD who speaks from the whirlwind.", themes: ["Suffering", "Sovereignty", "Faith", "Humility"], keyVerse: { ref: "Job 19:25", chapter: 19, verse: 25 } },
  { id: 19, slug: "psalms", name: "Psalms", abbr: "Ps", chapters: 150, testament: "OT", genre: "Wisdom", author: "David, Asaph, Korahites, others", date: "c. 1400–450 BC", summary: "Israel's prayer book and hymnal: 150 poems of praise, lament, thanksgiving, and hope that give voice to every season of the soul.", themes: ["Praise", "Lament", "Trust", "Messiah"], keyVerse: { ref: "Psalm 23:1", chapter: 23, verse: 1 } },
  { id: 20, slug: "proverbs", name: "Proverbs", abbr: "Prov", chapters: 31, testament: "OT", genre: "Wisdom", author: "Solomon, Agur, Lemuel", date: "c. 950–700 BC", summary: "Skill for living under God: short, sharp sayings about wisdom and folly, work and words, money, friendship, and the fear of the LORD.", themes: ["Wisdom", "Fear of the LORD", "Character", "Speech"], keyVerse: { ref: "Proverbs 3:5", chapter: 3, verse: 5 } },
  { id: 21, slug: "ecclesiastes", name: "Ecclesiastes", abbr: "Eccl", chapters: 12, testament: "OT", genre: "Wisdom", author: "Solomon (traditionally)", date: "c. 935 BC", summary: "The Preacher tests everything \"under the sun\" and finds it fleeting vapor — life's meaning is found only in fearing God and keeping His commands.", themes: ["Meaning", "Vanity", "Mortality", "Joy as gift"], keyVerse: { ref: "Ecclesiastes 12:13", chapter: 12, verse: 13 } },
  { id: 22, slug: "song-of-songs", name: "Song of Songs", abbr: "Song", chapters: 8, testament: "OT", genre: "Wisdom", author: "Solomon", date: "c. 960 BC", summary: "A lyrical celebration of covenant love and desire between bride and groom — love strong as death, a flame of the LORD.", themes: ["Love", "Marriage", "Desire", "Faithfulness"], keyVerse: { ref: "Song of Songs 8:7", chapter: 8, verse: 7 } },
  { id: 23, slug: "isaiah", name: "Isaiah", abbr: "Isa", chapters: 66, testament: "OT", genre: "Major Prophets", author: "Isaiah", date: "c. 700–680 BC", summary: "The prince of prophets: searing judgment, breathtaking comfort, and the Suffering Servant who bears the sins of many. Salvation belongs to the LORD.", themes: ["Holiness", "Judgment & comfort", "Messiah", "New creation"], keyVerse: { ref: "Isaiah 53:5", chapter: 53, verse: 5 } },
  { id: 24, slug: "jeremiah", name: "Jeremiah", abbr: "Jer", chapters: 52, testament: "OT", genre: "Major Prophets", author: "Jeremiah", date: "c. 626–580 BC", summary: "The weeping prophet pleads with Judah for forty years before the fall of Jerusalem, yet announces a new covenant written on hearts.", themes: ["Repentance", "New covenant", "Judgment", "Hope"], keyVerse: { ref: "Jeremiah 29:11", chapter: 29, verse: 11 } },
  { id: 25, slug: "lamentations", name: "Lamentations", abbr: "Lam", chapters: 5, testament: "OT", genre: "Major Prophets", author: "Jeremiah (traditionally)", date: "c. 586 BC", summary: "Five funeral poems over fallen Jerusalem — and at the center, defiant hope: His mercies are new every morning; great is His faithfulness.", themes: ["Grief", "Faithfulness", "Hope in ruin", "Mercy"], keyVerse: { ref: "Lamentations 3:22", chapter: 3, verse: 22 } },
  { id: 26, slug: "ezekiel", name: "Ezekiel", abbr: "Ezek", chapters: 48, testament: "OT", genre: "Major Prophets", author: "Ezekiel", date: "c. 593–570 BC", summary: "Visions by the rivers of Babylon: God's glory departs the temple, dry bones live again, and a river of life flows from a new temple.", themes: ["God's glory", "New heart", "Restoration", "Watchman"], keyVerse: { ref: "Ezekiel 36:26", chapter: 36, verse: 26 } },
  { id: 27, slug: "daniel", name: "Daniel", abbr: "Dan", chapters: 12, testament: "OT", genre: "Major Prophets", author: "Daniel", date: "c. 536 BC", summary: "Faithfulness in exile and visions of empires rising and falling — until the Ancient of Days gives an everlasting kingdom to one like a Son of Man.", themes: ["Sovereignty", "Faithfulness", "Kingdoms", "Son of Man"], keyVerse: { ref: "Daniel 2:44", chapter: 2, verse: 44 } },
  { id: 28, slug: "hosea", name: "Hosea", abbr: "Hos", chapters: 14, testament: "OT", genre: "Minor Prophets", author: "Hosea", date: "c. 755–710 BC", summary: "A prophet marries an unfaithful wife to embody God's scandalous, pursuing love for unfaithful Israel.", themes: ["Covenant love", "Unfaithfulness", "Redemption", "Return"], keyVerse: { ref: "Hosea 6:6", chapter: 6, verse: 6 } },
  { id: 29, slug: "joel", name: "Joel", abbr: "Joel", chapters: 3, testament: "OT", genre: "Minor Prophets", author: "Joel", date: "c. 835–796 BC", summary: "A locust plague previews the Day of the LORD. Rend your hearts — and God promises to pour out His Spirit on all flesh.", themes: ["Day of the LORD", "Repentance", "Spirit outpoured", "Restoration"], keyVerse: { ref: "Joel 2:28", chapter: 2, verse: 28 } },
  { id: 30, slug: "amos", name: "Amos", abbr: "Amos", chapters: 9, testament: "OT", genre: "Minor Prophets", author: "Amos", date: "c. 760–750 BC", summary: "A shepherd from Tekoa thunders against comfortable injustice: let justice roll down like waters, and righteousness like an ever-flowing stream.", themes: ["Justice", "Judgment", "Hypocrisy", "Restoration"], keyVerse: { ref: "Amos 5:24", chapter: 5, verse: 24 } },
  { id: 31, slug: "obadiah", name: "Obadiah", abbr: "Obad", chapters: 1, testament: "OT", genre: "Minor Prophets", author: "Obadiah", date: "c. 586 BC", summary: "The shortest OT book: Edom's pride in gloating over Judah's fall is judged, for the kingdom belongs to the LORD.", themes: ["Pride", "Judgment", "Brotherhood", "God's kingdom"], keyVerse: { ref: "Obadiah 1:15", chapter: 1, verse: 15 } },
  { id: 32, slug: "jonah", name: "Jonah", abbr: "Jonah", chapters: 4, testament: "OT", genre: "Minor Prophets", author: "Jonah", date: "c. 780–750 BC", summary: "A runaway prophet, a great fish, and a repentant pagan city reveal a God whose compassion is wider than His people's hearts.", themes: ["Mercy", "Mission", "Repentance", "Compassion"], keyVerse: { ref: "Jonah 4:2", chapter: 4, verse: 2 } },
  { id: 33, slug: "micah", name: "Micah", abbr: "Mic", chapters: 7, testament: "OT", genre: "Minor Prophets", author: "Micah", date: "c. 735–700 BC", summary: "Judgment on corrupt leaders, a ruler born in Bethlehem, and the summary of true religion: do justice, love mercy, walk humbly with your God.", themes: ["Justice", "Humility", "Messiah from Bethlehem", "Pardon"], keyVerse: { ref: "Micah 6:8", chapter: 6, verse: 8 } },
  { id: 34, slug: "nahum", name: "Nahum", abbr: "Nah", chapters: 3, testament: "OT", genre: "Minor Prophets", author: "Nahum", date: "c. 663–612 BC", summary: "Nineveh's reprieve (under Jonah) has run out: the LORD is slow to anger but will by no means clear the guilty. He is a stronghold for those who trust Him.", themes: ["Justice", "Wrath", "Refuge", "Sovereignty"], keyVerse: { ref: "Nahum 1:7", chapter: 1, verse: 7 } },
  { id: 35, slug: "habakkuk", name: "Habakkuk", abbr: "Hab", chapters: 3, testament: "OT", genre: "Minor Prophets", author: "Habakkuk", date: "c. 607 BC", summary: "A prophet interrogates God about evil and receives the anthem of faith: the righteous shall live by faith — and learns to rejoice even in barren times.", themes: ["Faith", "Theodicy", "Waiting", "Joy in God"], keyVerse: { ref: "Habakkuk 2:4", chapter: 2, verse: 4 } },
  { id: 36, slug: "zephaniah", name: "Zephaniah", abbr: "Zeph", chapters: 3, testament: "OT", genre: "Minor Prophets", author: "Zephaniah", date: "c. 630 BC", summary: "The great Day of the LORD sweeps the earth, yet ends in a song: the LORD your God is in your midst; He will rejoice over you with singing.", themes: ["Day of the LORD", "Humility", "Remnant", "God's delight"], keyVerse: { ref: "Zephaniah 3:17", chapter: 3, verse: 17 } },
  { id: 37, slug: "haggai", name: "Haggai", abbr: "Hag", chapters: 2, testament: "OT", genre: "Minor Prophets", author: "Haggai", date: "520 BC", summary: "\"Consider your ways\": Haggai stirs discouraged returnees to finish God's house, with the promise that the latter glory will surpass the former.", themes: ["Priorities", "God's house", "Encouragement", "Glory"], keyVerse: { ref: "Haggai 2:9", chapter: 2, verse: 9 } },
  { id: 38, slug: "zechariah", name: "Zechariah", abbr: "Zech", chapters: 14, testament: "OT", genre: "Minor Prophets", author: "Zechariah", date: "c. 520–480 BC", summary: "Night visions and messianic prophecy: a king riding on a donkey, a pierced shepherd, a fountain opened for sin — the LORD will be king over all the earth.", themes: ["Messiah", "Restoration", "Spirit not might", "God's kingship"], keyVerse: { ref: "Zechariah 4:6", chapter: 4, verse: 6 } },
  { id: 39, slug: "malachi", name: "Malachi", abbr: "Mal", chapters: 4, testament: "OT", genre: "Minor Prophets", author: "Malachi", date: "c. 430 BC", summary: "The OT closes with a dispute: half-hearted worship meets a God of unchanging love, who promises the sun of righteousness and a forerunner like Elijah.", themes: ["Wholehearted worship", "God's love", "Faithfulness", "Forerunner"], keyVerse: { ref: "Malachi 3:6", chapter: 3, verse: 6 } },
  { id: 40, slug: "matthew", name: "Matthew", abbr: "Matt", chapters: 28, testament: "NT", genre: "Gospels", author: "Matthew (Levi)", date: "c. AD 55–65", summary: "Jesus is the promised Messiah-King, son of David and Abraham. Five great teaching blocks — including the Sermon on the Mount — reveal life in His kingdom.", themes: ["Kingdom of heaven", "Fulfillment", "Discipleship", "Great Commission"], keyVerse: { ref: "Matthew 28:19", chapter: 28, verse: 19 } },
  { id: 41, slug: "mark", name: "Mark", abbr: "Mark", chapters: 16, testament: "NT", genre: "Gospels", author: "John Mark", date: "c. AD 50–60", summary: "The fast-moving Gospel of the Servant-King: Jesus acts with authority, suffers deliberately, and gives His life as a ransom for many.", themes: ["Servanthood", "Authority", "The cross", "Faith"], keyVerse: { ref: "Mark 10:45", chapter: 10, verse: 45 } },
  { id: 42, slug: "luke", name: "Luke", abbr: "Luke", chapters: 24, testament: "NT", genre: "Gospels", author: "Luke the physician", date: "c. AD 60–62", summary: "A careful historian presents Jesus as the Son of Man who seeks and saves the lost — with special love for outsiders, the poor, and the overlooked.", themes: ["Salvation for all", "Compassion", "Prayer", "Joy"], keyVerse: { ref: "Luke 19:10", chapter: 19, verse: 10 } },
  { id: 43, slug: "john", name: "John", abbr: "John", chapters: 21, testament: "NT", genre: "Gospels", author: "John the apostle", date: "c. AD 85–95", summary: "The Word became flesh. Seven signs and seven \"I am\" sayings unveil Jesus as the Son of God, that believing you may have life in His name.", themes: ["Belief", "Eternal life", "Light & darkness", "Love"], keyVerse: { ref: "John 3:16", chapter: 3, verse: 16 } },
  { id: 44, slug: "acts", name: "Acts", abbr: "Acts", chapters: 28, testament: "NT", genre: "Acts", author: "Luke the physician", date: "c. AD 62", summary: "The risen Jesus pours out the Spirit and the gospel explodes from Jerusalem to Rome through the witness of Peter, Paul, and the young church.", themes: ["Holy Spirit", "Witness", "Church", "Unstoppable gospel"], keyVerse: { ref: "Acts 1:8", chapter: 1, verse: 8 } },
  { id: 45, slug: "romans", name: "Romans", abbr: "Rom", chapters: 16, testament: "NT", genre: "Pauline Epistles", author: "Paul", date: "c. AD 57", summary: "Paul's magnum opus: all have sinned, all may be justified freely by grace through faith in Christ, and nothing can separate us from God's love.", themes: ["Justification", "Grace", "Faith", "New life in the Spirit"], keyVerse: { ref: "Romans 8:28", chapter: 8, verse: 28 } },
  { id: 46, slug: "1-corinthians", name: "1 Corinthians", abbr: "1Cor", chapters: 16, testament: "NT", genre: "Pauline Epistles", author: "Paul", date: "c. AD 55", summary: "A gifted but fractured church learns that the cross confounds worldly wisdom, love surpasses every gift, and resurrection changes everything.", themes: ["Unity", "Love", "Resurrection", "Holiness"], keyVerse: { ref: "1 Corinthians 13:13", chapter: 13, verse: 13 } },
  { id: 47, slug: "2-corinthians", name: "2 Corinthians", abbr: "2Cor", chapters: 13, testament: "NT", genre: "Pauline Epistles", author: "Paul", date: "c. AD 56", summary: "Paul's most personal letter: treasure in jars of clay, strength perfected in weakness, and the ministry of reconciliation.", themes: ["Weakness & power", "Comfort", "Reconciliation", "Generosity"], keyVerse: { ref: "2 Corinthians 5:17", chapter: 5, verse: 17 } },
  { id: 48, slug: "galatians", name: "Galatians", abbr: "Gal", chapters: 6, testament: "NT", genre: "Pauline Epistles", author: "Paul", date: "c. AD 48–49", summary: "A fiery defense of the gospel of grace: justified by faith apart from works of the law, we stand fast in the freedom for which Christ set us free.", themes: ["Freedom", "Grace vs. law", "Faith", "Fruit of the Spirit"], keyVerse: { ref: "Galatians 2:20", chapter: 2, verse: 20 } },
  { id: 49, slug: "ephesians", name: "Ephesians", abbr: "Eph", chapters: 6, testament: "NT", genre: "Pauline Epistles", author: "Paul", date: "c. AD 60–62", summary: "Every spiritual blessing in Christ: chosen, redeemed, made alive, united in one new humanity — now walk worthy and stand firm in God's armor.", themes: ["In Christ", "Grace", "Church as body", "Spiritual warfare"], keyVerse: { ref: "Ephesians 2:8", chapter: 2, verse: 8 } },
  { id: 50, slug: "philippians", name: "Philippians", abbr: "Phil", chapters: 4, testament: "NT", genre: "Pauline Epistles", author: "Paul", date: "c. AD 61", summary: "Joy from a prison cell: the mind of Christ who humbled Himself, contentment in every circumstance, and pressing on toward the prize.", themes: ["Joy", "Humility", "Contentment", "Christ above all"], keyVerse: { ref: "Philippians 4:13", chapter: 4, verse: 13 } },
  { id: 51, slug: "colossians", name: "Colossians", abbr: "Col", chapters: 4, testament: "NT", genre: "Pauline Epistles", author: "Paul", date: "c. AD 60–62", summary: "Christ is supreme — creator, sustainer, head of the church, fullness of God — and you are complete in Him. Set your mind on things above.", themes: ["Supremacy of Christ", "Fullness", "New self", "Thankfulness"], keyVerse: { ref: "Colossians 1:17", chapter: 1, verse: 17 } },
  { id: 52, slug: "1-thessalonians", name: "1 Thessalonians", abbr: "1Thess", chapters: 5, testament: "NT", genre: "Pauline Epistles", author: "Paul", date: "c. AD 51", summary: "Encouragement for a young persecuted church: live to please God, grieve with hope, for the Lord Himself will descend and we will be with Him forever.", themes: ["Hope", "Christ's return", "Holy living", "Encouragement"], keyVerse: { ref: "1 Thessalonians 5:16", chapter: 5, verse: 16 } },
  { id: 53, slug: "2-thessalonians", name: "2 Thessalonians", abbr: "2Thess", chapters: 3, testament: "NT", genre: "Pauline Epistles", author: "Paul", date: "c. AD 51–52", summary: "Stand firm: the Day of the Lord has not yet come. Until it does, don't be idle — work quietly and never tire of doing good.", themes: ["Perseverance", "Day of the Lord", "Work", "Steadfastness"], keyVerse: { ref: "2 Thessalonians 3:3", chapter: 3, verse: 3 } },
  { id: 54, slug: "1-timothy", name: "1 Timothy", abbr: "1Tim", chapters: 6, testament: "NT", genre: "Pauline Epistles", author: "Paul", date: "c. AD 62–64", summary: "A mentor's manual for church life: sound doctrine, qualified leaders, godliness with contentment, and fighting the good fight of faith.", themes: ["Sound doctrine", "Leadership", "Godliness", "Contentment"], keyVerse: { ref: "1 Timothy 4:12", chapter: 4, verse: 12 } },
  { id: 55, slug: "2-timothy", name: "2 Timothy", abbr: "2Tim", chapters: 4, testament: "NT", genre: "Pauline Epistles", author: "Paul", date: "c. AD 66–67", summary: "Paul's last words: guard the gospel, endure suffering, preach the Word. All Scripture is God-breathed; a crown of righteousness awaits.", themes: ["Endurance", "Scripture", "Faithfulness", "Legacy"], keyVerse: { ref: "2 Timothy 3:16", chapter: 3, verse: 16 } },
  { id: 56, slug: "titus", name: "Titus", abbr: "Titus", chapters: 3, testament: "NT", genre: "Pauline Epistles", author: "Paul", date: "c. AD 62–64", summary: "Grace that trains: sound doctrine adorned by good works on the island of Crete, because the grace of God has appeared bringing salvation.", themes: ["Grace that transforms", "Good works", "Order", "Sound teaching"], keyVerse: { ref: "Titus 2:11", chapter: 2, verse: 11 } },
  { id: 57, slug: "philemon", name: "Philemon", abbr: "Phlm", chapters: 1, testament: "NT", genre: "Pauline Epistles", author: "Paul", date: "c. AD 60–62", summary: "One page that undermines slavery from the inside: receive runaway Onesimus back \"no longer as a slave, but as a beloved brother.\"", themes: ["Forgiveness", "Brotherhood", "Reconciliation", "Appeal of love"], keyVerse: { ref: "Philemon 1:16", chapter: 1, verse: 16 } },
  { id: 58, slug: "hebrews", name: "Hebrews", abbr: "Heb", chapters: 13, testament: "NT", genre: "General Epistles", author: "Unknown", date: "c. AD 64–68", summary: "Jesus is better — than angels, Moses, and the old priesthood. A great high priest and a once-for-all sacrifice call us to draw near and hold fast.", themes: ["Supremacy of Christ", "Faith", "Perseverance", "New covenant"], keyVerse: { ref: "Hebrews 12:2", chapter: 12, verse: 2 } },
  { id: 59, slug: "james", name: "James", abbr: "Jas", chapters: 5, testament: "NT", genre: "General Epistles", author: "James, brother of Jesus", date: "c. AD 44–49", summary: "Wisdom with work boots on: faith without works is dead. Count trials as joy, bridle the tongue, care for the vulnerable, pray in faith.", themes: ["Living faith", "Trials", "The tongue", "Wisdom"], keyVerse: { ref: "James 1:22", chapter: 1, verse: 22 } },
  { id: 60, slug: "1-peter", name: "1 Peter", abbr: "1Pet", chapters: 5, testament: "NT", genre: "General Epistles", author: "Peter", date: "c. AD 62–64", summary: "A living hope for exiles under fire: chosen strangers called to holiness, honorable conduct, and unashamed suffering for Christ's name.", themes: ["Living hope", "Suffering", "Holiness", "Identity"], keyVerse: { ref: "1 Peter 5:7", chapter: 5, verse: 7 } },
  { id: 61, slug: "2-peter", name: "2 Peter", abbr: "2Pet", chapters: 3, testament: "NT", genre: "General Epistles", author: "Peter", date: "c. AD 65–68", summary: "Grow in grace and knowledge; beware false teachers; and remember — the Lord is not slow, but patient, not wishing that any should perish.", themes: ["Growth", "Truth vs. error", "Christ's return", "Patience of God"], keyVerse: { ref: "2 Peter 3:9", chapter: 3, verse: 9 } },
  { id: 62, slug: "1-john", name: "1 John", abbr: "1John", chapters: 5, testament: "NT", genre: "General Epistles", author: "John the apostle", date: "c. AD 85–95", summary: "Tests of authentic life with God: walk in the light, love one another, believe in the Son — that you may know you have eternal life.", themes: ["Assurance", "Love", "Light", "Truth"], keyVerse: { ref: "1 John 4:19", chapter: 4, verse: 19 } },
  { id: 63, slug: "2-john", name: "2 John", abbr: "2John", chapters: 1, testament: "NT", genre: "General Epistles", author: "John the apostle", date: "c. AD 85–95", summary: "Walk in truth and love — but do not open the door to those who deny Christ come in the flesh.", themes: ["Truth", "Love", "Discernment", "Faithfulness"], keyVerse: { ref: "2 John 1:6", chapter: 1, verse: 6 } },
  { id: 64, slug: "3-john", name: "3 John", abbr: "3John", chapters: 1, testament: "NT", genre: "General Epistles", author: "John the apostle", date: "c. AD 85–95", summary: "A postcard about hospitality: imitate good, not evil — support gospel workers like Gaius, not gatekeepers like Diotrephes.", themes: ["Hospitality", "Humility", "Imitation", "Truth"], keyVerse: { ref: "3 John 1:4", chapter: 1, verse: 4 } },
  { id: 65, slug: "jude", name: "Jude", abbr: "Jude", chapters: 1, testament: "NT", genre: "General Epistles", author: "Jude, brother of Jesus", date: "c. AD 65–80", summary: "Contend for the faith once for all delivered to the saints — and rest in Him who is able to keep you from stumbling.", themes: ["Contending", "Apostasy", "Kept by God", "Mercy"], keyVerse: { ref: "Jude 1:24", chapter: 1, verse: 24 } },
  { id: 66, slug: "revelation", name: "Revelation", abbr: "Rev", chapters: 22, testament: "NT", genre: "Apocalyptic", author: "John the apostle", date: "c. AD 95", summary: "The unveiling of Jesus Christ: the Lamb on the throne, judgment and victory, and a new heaven and new earth where God wipes away every tear.", themes: ["Christ's victory", "Worship", "Perseverance", "New creation"], keyVerse: { ref: "Revelation 21:4", chapter: 21, verse: 4 } },
];

const bySlug = new Map(BOOKS.map((b) => [b.slug, b]));
const byId = new Map(BOOKS.map((b) => [b.id, b]));

export function getBookBySlug(slug: string): Book | undefined {
  return bySlug.get(slug);
}

export function getBookById(id: number): Book | undefined {
  return byId.get(id);
}

export const OLD_TESTAMENT = BOOKS.filter((b) => b.testament === "OT");
export const NEW_TESTAMENT = BOOKS.filter((b) => b.testament === "NT");

export const GENRE_COLORS: Record<Genre, string> = {
  Law: "bg-amber-500/12 text-amber-700 dark:text-amber-400",
  History: "bg-orange-500/12 text-orange-700 dark:text-orange-400",
  Wisdom: "bg-emerald-500/12 text-emerald-700 dark:text-emerald-400",
  "Major Prophets": "bg-sky-500/12 text-sky-700 dark:text-sky-400",
  "Minor Prophets": "bg-cyan-500/12 text-cyan-700 dark:text-cyan-400",
  Gospels: "bg-violet-500/12 text-violet-700 dark:text-violet-400",
  Acts: "bg-fuchsia-500/12 text-fuchsia-700 dark:text-fuchsia-400",
  "Pauline Epistles": "bg-rose-500/12 text-rose-700 dark:text-rose-400",
  "General Epistles": "bg-pink-500/12 text-pink-700 dark:text-pink-400",
  Apocalyptic: "bg-indigo-500/12 text-indigo-700 dark:text-indigo-400",
};
