export type QuizDifficulty = "easy" | "medium" | "hard";

export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  /** index into options */
  answer: number;
  explanation: string;
  reference: string;
  difficulty: QuizDifficulty;
  category: string;
}

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  { id: "q1", question: "How many days did God take to create the heavens and the earth before resting?", options: ["Five", "Six", "Seven", "Eight"], answer: 1, explanation: "God created in six days and rested on the seventh, setting the pattern for the Sabbath.", reference: "Genesis 1–2:3", difficulty: "easy", category: "Old Testament" },
  { id: "q2", question: "Who built the ark that saved his family from the flood?", options: ["Abraham", "Moses", "Noah", "Enoch"], answer: 2, explanation: "Noah found grace in the eyes of the LORD and obeyed God's command to build the ark.", reference: "Genesis 6–9", difficulty: "easy", category: "Old Testament" },
  { id: "q3", question: "What sea did God part so Israel could escape Egypt?", options: ["The Dead Sea", "The Sea of Galilee", "The Mediterranean Sea", "The Red Sea"], answer: 3, explanation: "God drove back the Red Sea by a strong east wind and Israel crossed on dry ground.", reference: "Exodus 14", difficulty: "easy", category: "Old Testament" },
  { id: "q4", question: "On what mountain did Moses receive the Ten Commandments?", options: ["Mount Sinai", "Mount Nebo", "Mount Carmel", "Mount Zion"], answer: 0, explanation: "The LORD descended on Mount Sinai in fire and gave Moses the tablets of the covenant.", reference: "Exodus 19–20", difficulty: "easy", category: "Old Testament" },
  { id: "q5", question: "Which shepherd boy defeated the giant Goliath?", options: ["Saul", "David", "Jonathan", "Samuel"], answer: 1, explanation: "David defeated Goliath with a sling and a stone, declaring 'the battle is the LORD's.'", reference: "1 Samuel 17", difficulty: "easy", category: "Old Testament" },
  { id: "q6", question: "Who was swallowed by a great fish after fleeing God's call?", options: ["Elijah", "Amos", "Jonah", "Hosea"], answer: 2, explanation: "Jonah fled to Tarshish instead of Nineveh; the LORD appointed a great fish to swallow him for three days.", reference: "Jonah 1–2", difficulty: "easy", category: "Old Testament" },
  { id: "q7", question: "In what town was Jesus born?", options: ["Nazareth", "Jerusalem", "Bethlehem", "Capernaum"], answer: 2, explanation: "As Micah prophesied, the Messiah was born in Bethlehem, the city of David.", reference: "Luke 2; Micah 5:2", difficulty: "easy", category: "Life of Jesus" },
  { id: "q8", question: "How many disciples did Jesus choose as apostles?", options: ["Seven", "Ten", "Twelve", "Seventy"], answer: 2, explanation: "Jesus appointed twelve, echoing the twelve tribes of Israel.", reference: "Mark 3:13–19", difficulty: "easy", category: "Life of Jesus" },
  { id: "q9", question: "What was Jesus' first recorded miracle?", options: ["Healing a leper", "Walking on water", "Feeding the 5,000", "Turning water into wine"], answer: 3, explanation: "At a wedding in Cana of Galilee, Jesus turned water into wine — the first of His signs.", reference: "John 2:1–11", difficulty: "easy", category: "Life of Jesus" },
  { id: "q10", question: "Who baptized Jesus in the Jordan River?", options: ["Peter", "John the Baptist", "Andrew", "Nicodemus"], answer: 1, explanation: "John baptized Jesus, and the Spirit descended like a dove as the Father spoke from heaven.", reference: "Matthew 3:13–17", difficulty: "easy", category: "Life of Jesus" },
  { id: "q11", question: "Complete the verse: 'For God so loved the world, that he gave his only begotten ___.'", options: ["Word", "Son", "Spirit", "Lamb"], answer: 1, explanation: "John 3:16 is the gospel in miniature: God gave His only begotten Son so believers may have everlasting life.", reference: "John 3:16", difficulty: "easy", category: "Famous Verses" },
  { id: "q12", question: "'The LORD is my ___; I shall not want.'", options: ["fortress", "shepherd", "light", "rock"], answer: 1, explanation: "Psalm 23 pictures the LORD as a shepherd who provides, leads, and protects.", reference: "Psalm 23:1", difficulty: "easy", category: "Famous Verses" },
  { id: "q13", question: "How many books are in the Protestant Bible?", options: ["27", "39", "66", "73"], answer: 2, explanation: "39 Old Testament books and 27 New Testament books make 66.", reference: "—", difficulty: "easy", category: "Bible Knowledge" },
  { id: "q14", question: "Which book comes first: Psalms or Proverbs?", options: ["Psalms", "Proverbs"], answer: 0, explanation: "The order of the wisdom books is Job, Psalms, Proverbs, Ecclesiastes, Song of Songs.", reference: "—", difficulty: "easy", category: "Bible Knowledge" },
  { id: "q15", question: "Who denied Jesus three times before the rooster crowed?", options: ["Judas", "Thomas", "Peter", "John"], answer: 2, explanation: "Peter denied the Lord three times, wept bitterly — and was later restored three times by the risen Jesus.", reference: "Luke 22:54–62; John 21", difficulty: "easy", category: "Life of Jesus" },
  { id: "q16", question: "Which two Old Testament figures appeared with Jesus at the transfiguration?", options: ["Abraham and Isaac", "Moses and Elijah", "David and Solomon", "Enoch and Noah"], answer: 1, explanation: "Moses (the Law) and Elijah (the Prophets) appeared in glory, testifying that Jesus fulfills both.", reference: "Matthew 17:1–8", difficulty: "medium", category: "Life of Jesus" },
  { id: "q17", question: "Who interpreted Pharaoh's dreams of seven fat and seven lean cows?", options: ["Daniel", "Joseph", "Moses", "Aaron"], answer: 1, explanation: "Joseph, raised from prison, interpreted the dreams as seven years of plenty and seven of famine.", reference: "Genesis 41", difficulty: "medium", category: "Old Testament" },
  { id: "q18", question: "Which prophet confronted the prophets of Baal on Mount Carmel?", options: ["Elisha", "Isaiah", "Elijah", "Jeremiah"], answer: 2, explanation: "Fire fell from heaven and consumed Elijah's sacrifice, and the people cried 'The LORD, he is God!'", reference: "1 Kings 18", difficulty: "medium", category: "Old Testament" },
  { id: "q19", question: "Who was the queen who saved her people 'for such a time as this'?", options: ["Ruth", "Deborah", "Esther", "Abigail"], answer: 2, explanation: "Esther risked her life before King Ahasuerus, and the Jews were delivered from Haman's plot.", reference: "Esther 4–7", difficulty: "medium", category: "Old Testament" },
  { id: "q20", question: "Which book contains the verse 'The just shall live by his faith'?", options: ["Isaiah", "Habakkuk", "Hosea", "Malachi"], answer: 1, explanation: "Habakkuk 2:4 became the seed text for Romans, Galatians, and Hebrews — and the Reformation.", reference: "Habakkuk 2:4", difficulty: "hard", category: "Old Testament" },
  { id: "q21", question: "How many people were saved on Noah's ark?", options: ["Four", "Six", "Eight", "Twelve"], answer: 2, explanation: "Noah, his wife, his three sons, and their wives — eight souls saved through water.", reference: "1 Peter 3:20", difficulty: "medium", category: "Old Testament" },
  { id: "q22", question: "What did Jesus feed to the 5,000?", options: ["Two loaves and five fish", "Five loaves and two fish", "Seven loaves and three fish", "Bread and wine"], answer: 1, explanation: "From a boy's five barley loaves and two small fish, Jesus fed thousands — with twelve baskets left over.", reference: "John 6:1–14", difficulty: "easy", category: "Life of Jesus" },
  { id: "q23", question: "Which apostle was a tax collector before following Jesus?", options: ["Matthew", "Mark", "Luke", "John"], answer: 0, explanation: "Matthew (also called Levi) left his tax booth to follow Jesus and later wrote the first Gospel.", reference: "Matthew 9:9", difficulty: "medium", category: "Life of Jesus" },
  { id: "q24", question: "On the road to which city was Saul converted?", options: ["Antioch", "Jerusalem", "Damascus", "Tarsus"], answer: 2, explanation: "A light from heaven stopped Saul near Damascus, and the persecutor became the apostle Paul.", reference: "Acts 9", difficulty: "medium", category: "Early Church" },
  { id: "q25", question: "At Pentecost, what appeared over the disciples as the Spirit came?", options: ["A dove", "Tongues of fire", "A cloud of glory", "Angels"], answer: 1, explanation: "Divided tongues as of fire rested on each of them, and they spoke in other languages.", reference: "Acts 2:1–4", difficulty: "medium", category: "Early Church" },
  { id: "q26", question: "Which epistle says 'faith without works is dead'?", options: ["Romans", "Galatians", "James", "1 Peter"], answer: 2, explanation: "James insists genuine faith always produces action — 'be doers of the word.'", reference: "James 2:26", difficulty: "medium", category: "Epistles" },
  { id: "q27", question: "The 'love chapter' — 'love is patient, love is kind' — is found in…", options: ["Romans 8", "1 Corinthians 13", "Ephesians 5", "1 John 4"], answer: 1, explanation: "Paul places the hymn to love at the center of his correction of the Corinthians' misuse of gifts.", reference: "1 Corinthians 13", difficulty: "easy", category: "Epistles" },
  { id: "q28", question: "How many fruit of the Spirit does Paul list in Galatians?", options: ["Seven", "Eight", "Nine", "Twelve"], answer: 2, explanation: "Love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control.", reference: "Galatians 5:22–23", difficulty: "medium", category: "Epistles" },
  { id: "q29", question: "Which is the shortest verse in the English Bible?", options: ["'Rejoice evermore.'", "'Jesus wept.'", "'Pray without ceasing.'", "'God is love.'"], answer: 1, explanation: "'Jesus wept' (John 11:35) — two words revealing the compassion of the Son of God at Lazarus' tomb.", reference: "John 11:35", difficulty: "medium", category: "Bible Knowledge" },
  { id: "q30", question: "What is the longest chapter in the Bible?", options: ["Psalm 78", "Psalm 119", "Isaiah 53", "Numbers 7"], answer: 1, explanation: "Psalm 119 has 176 verses — an acrostic poem celebrating God's Word in nearly every line.", reference: "Psalm 119", difficulty: "medium", category: "Bible Knowledge" },
  { id: "q31", question: "Which prophet saw a valley of dry bones come to life?", options: ["Isaiah", "Jeremiah", "Ezekiel", "Daniel"], answer: 2, explanation: "Ezekiel's vision pictured God breathing new life into exiled, hopeless Israel.", reference: "Ezekiel 37", difficulty: "medium", category: "Old Testament" },
  { id: "q32", question: "Who were thrown into the fiery furnace for refusing to worship an image?", options: ["Daniel and his friends", "Shadrach, Meshach, and Abednego", "Elijah and Elisha", "Ezra and Nehemiah"], answer: 1, explanation: "A fourth figure walked with them in the flames, and they emerged without even the smell of smoke.", reference: "Daniel 3", difficulty: "medium", category: "Old Testament" },
  { id: "q33", question: "What relationship was Ruth to Naomi?", options: ["Sister", "Daughter", "Daughter-in-law", "Cousin"], answer: 2, explanation: "Ruth, Naomi's Moabite daughter-in-law, pledged: 'Your people shall be my people, and your God my God.'", reference: "Ruth 1:16", difficulty: "medium", category: "Old Testament" },
  { id: "q34", question: "Which Gospel was written by a physician?", options: ["Matthew", "Mark", "Luke", "John"], answer: 2, explanation: "Paul calls Luke 'the beloved physician' (Colossians 4:14); he also wrote Acts.", reference: "Colossians 4:14", difficulty: "medium", category: "Bible Knowledge" },
  { id: "q35", question: "In Revelation, what title does the risen Jesus claim?", options: ["Alpha and Omega", "Rose of Sharon", "Balm of Gilead", "Star of Jacob"], answer: 0, explanation: "'I am the Alpha and the Omega, the first and the last, the beginning and the end.'", reference: "Revelation 22:13", difficulty: "medium", category: "New Testament" },
  { id: "q36", question: "What was Paul's occupation by trade?", options: ["Fisherman", "Carpenter", "Tentmaker", "Scribe"], answer: 2, explanation: "Paul supported his ministry making tents, working with Aquila and Priscilla in Corinth.", reference: "Acts 18:1–3", difficulty: "hard", category: "Early Church" },
  { id: "q37", question: "Which king saw handwriting on the wall the night his kingdom fell?", options: ["Nebuchadnezzar", "Belshazzar", "Darius", "Cyrus"], answer: 1, explanation: "MENE, MENE, TEKEL, UPHARSIN — Belshazzar was weighed in the balances and found wanting.", reference: "Daniel 5", difficulty: "hard", category: "Old Testament" },
  { id: "q38", question: "Melchizedek, to whom Abraham gave a tenth, was king of…", options: ["Sodom", "Salem", "Gerar", "Egypt"], answer: 1, explanation: "Melchizedek, king of Salem and priest of God Most High, prefigures Christ's eternal priesthood (Hebrews 7).", reference: "Genesis 14:18", difficulty: "hard", category: "Old Testament" },
  { id: "q39", question: "Which epistle never mentions God's name directly — wait, that's Esther. Which NT book is a single chapter written to a slave owner?", options: ["Jude", "Philemon", "2 John", "3 John"], answer: 1, explanation: "Paul appeals to Philemon to receive back Onesimus 'no longer as a slave, but as a beloved brother.'", reference: "Philemon", difficulty: "hard", category: "Epistles" },
  { id: "q40", question: "How many churches receive letters in Revelation 2–3?", options: ["Five", "Six", "Seven", "Twelve"], answer: 2, explanation: "Ephesus, Smyrna, Pergamum, Thyatira, Sardis, Philadelphia, and Laodicea.", reference: "Revelation 2–3", difficulty: "hard", category: "New Testament" },
  { id: "q41", question: "Who is the only woman with a book named after her in both Testaments — trick question! Which two OT books are named after women?", options: ["Ruth and Esther", "Ruth and Deborah", "Esther and Miriam", "Hannah and Ruth"], answer: 0, explanation: "Ruth, a Gentile who joined Israel, and Esther, a Jew in a Gentile court — mirror images of God's providence.", reference: "Ruth; Esther", difficulty: "medium", category: "Bible Knowledge" },
  { id: "q42", question: "What did God provide Abraham as a substitute sacrifice for Isaac?", options: ["A lamb", "A ram caught in a thicket", "A dove", "A bull"], answer: 1, explanation: "'God will provide himself a lamb' — a ram was caught by its horns, and the place was named 'The LORD will provide.'", reference: "Genesis 22:13–14", difficulty: "medium", category: "Old Testament" },
  { id: "q43", question: "Which disciple doubted the resurrection until he saw Jesus' wounds?", options: ["Philip", "Andrew", "Thomas", "Bartholomew"], answer: 2, explanation: "Thomas confessed 'My Lord and my God!' — and Jesus blessed all who believe without seeing.", reference: "John 20:24–29", difficulty: "easy", category: "Life of Jesus" },
  { id: "q44", question: "What is the last word of the Bible?", options: ["Forever", "Amen", "Come", "Grace"], answer: 1, explanation: "'The grace of our Lord Jesus Christ be with you all. Amen.' (Revelation 22:21)", reference: "Revelation 22:21", difficulty: "hard", category: "Bible Knowledge" },
  { id: "q45", question: "Which prophet was taken to heaven in a whirlwind with chariots of fire?", options: ["Enoch", "Moses", "Elijah", "Isaiah"], answer: 2, explanation: "Elijah was taken up while Elisha watched, receiving a double portion of his spirit.", reference: "2 Kings 2:11", difficulty: "medium", category: "Old Testament" },
  { id: "q46", question: "Complete: 'I can do all things through ___ which strengtheneth me.'", options: ["faith", "Christ", "prayer", "hope"], answer: 1, explanation: "Paul's secret of contentment in every circumstance was the strength of Christ Himself.", reference: "Philippians 4:13", difficulty: "easy", category: "Famous Verses" },
  { id: "q47", question: "Where was Jesus crucified?", options: ["Gethsemane", "Golgotha", "Mount Sinai", "Bethany"], answer: 1, explanation: "Golgotha, 'the place of a skull,' outside Jerusalem's walls.", reference: "John 19:17–18", difficulty: "easy", category: "Life of Jesus" },
  { id: "q48", question: "How many days was Jesus in the tomb?", options: ["One", "Two", "Three", "Seven"], answer: 2, explanation: "As Jonah was three days in the fish, so the Son of Man was three days in the heart of the earth.", reference: "Matthew 12:40", difficulty: "easy", category: "Life of Jesus" },
];

export const QUIZ_CATEGORIES = [...new Set(QUIZ_QUESTIONS.map((q) => q.category))];
